### ISSUE TITLE
Source of github pages documentation

### ISSUE THREAD

**Issue by Maetveis** [ROCmSoftwarePlatform/hipfort#100]
Hi,

I'm working on #99 as part of the ROCm documentation team / effort.

I have stumbled upon the github pages based documentation for hipfort at https://rocmsoftwareplatform.github.io/hipfort/ . As far as I can see the source of this build (i.e. the Doxyfile) is not published.

Is this available somewhere or would you be able to share it? I would like to consult it as I'm missing the documentation of some of the modules  compared to it in #99 (e.g. compare https://rocmsoftwareplatform.github.io/hipfort/namespaces.html with https://advanced-micro-devices-demo--99.com.readthedocs.build/projects/hipfort/en/99/doxygen/html/namespaces.html e.g. `hipfort` is missing).

**Comment by domcharrier** [comment]
> I see an explicit preprocessing (with gfortran) of the fortran files, but doxygen can also run the preprocessor during its build, what is the reason for this explicit step? (I'm not super familiar with fortran, and how well doxygen supports it, so I'm not sure, but this could be the reason why the modules don't show for me?)

The `Doxyfile` uses doxygen's 

`PREDEFINED             = USE_FPOINTER_INTERFACES USE_CUDA_NAMES`

preprocessor option (https://github.com/ROCmSoftwarePlatform/hipfort/blob/repo-docs-build-5.0.0/docs/Doxyfile#L24)
Is this what you mean?

I assume this triggers the gfortran call.

Any other tools  involved aside from doxygen on your side?

**Comment by domcharrier** [comment]
Ah, I see. I don't remember exactly why I did that but:

It could be because the Fortran sources use C preprocessor directives (macros starting with `#` are not part of the 
Fortran standard). To use that feature with `gfortran`, you need to specify the `-cpp` switch.

It appears I wasn't able to find a way to get doxygen to enable this non-standard feature of gfortran.

Note further that there is a difference in the predefined macros.
In the `clean-module-files.sh`, we have

`-DUSE_FPOINTER_INTERFACES -UUSE_CUDA_NAMES`

which is correct IMO.

**Comment by Maetveis** [comment]
In the end I added the same pre-processing as you had, just driven from python. Thank you very much for the help I'll close this issue.
