### ISSUE TITLE
Extending hipHostMalloc Interface

### ISSUE THREAD

**Issue by pbauman** [ROCmSoftwarePlatform/hipfort#7]
This is attempting to think ahead a bit and solicit thoughts on what the right thing to do will be. I anticipate this will be one of the first questions from customers. Capturing the thought for now.

If was a Fortran user, and I needed to hipHostMalloc my array, I would like the interface to look Fortran-esque. Something akin to

<pre>
integer, pointer, dimension(:,:,:)  :: foo
hipCheck(hipHostMalloc3d(foo, [nx,ny,nz]))
</pre>

Since the memory is being malloc'ed on the C-side, the usual thing to do is something like

<pre>
double precision, pointer, dimension(:,:,:) :: x
type(c_ptr) :: buffer = c_null_ptr
...
call hipCheck(hipHostMalloc(buffer,n_bytes,0))
call c_f_pointer(buffer,x,[N,N,N])
...
call hipCheck(hipHostFree(buffer))
</pre>

So what's the right way to handle the buffer? It would be nice if we could make that invisible to the Fortran users and provide them a clean interface for hipHostMalloc.

Or maybe there is better ideas for the interface than I have.

**Comment by txomin13** [comment]
The main difficulty here is to deduce the datatype of the variable in order to derive the number
of bytes per element.
Furthermore, we need to map the Fortran pointer `x` to a `type(c_ptr)` when calling
`hipHostFree`.

**Some ideas we can try out:**

  1) Potentially, we are able to support this syntax by overloading the `hipHostFree` and `hipHostMalloc` definitions 
*Fortran overloading example:*
https://stackoverflow.com/questions/13721961/overloading-functions-with-fortran

* Via overloading we could deduce the type and thus the bytes per element. With this information, we can call the classic ISO C `hipHostMalloc` interface from an overloaded subroutine for `double precision` arrays.
* When we call the overloaded `hipHostFree(x)` subroutine for `double precision` host arrays,  we can further call `c_loc(x)` to deduce the `type(c_ptr)` that we pass to the classic ISO C `hipHostFree` interface. 

2) There might be a generic way to implement both via `type(*)` assumed-type variables
but I do not have much experience with those and I am also not sure how well they are supported
by gfortran.
(mpi_f08 bindings use them a lot and could give us some guidance):
*Example:*
https://groups.google.com/forum/#!topic/comp.lang.fortran/xMcNMaaQI6g

**Comment by pbauman** [comment]
Thanks @txomin13 . I think those are good ideas to explore. I'll be honest, I wasn't actually thinking about trying to overload the existing interface, but rather we could extend (e.g. `hipHostMalloc3df`), but then the question is where to put that? @gregrodgers had already been anticipating user contributions beyond the existing HIP API and I was imaging something like using Fortran-style arrays would be one such example. Either way, we need to decide how to handle API extensions, where to put them, etc. I do think they should live separately from the "official" HIP API. But that's just my opinion, others should chime in.

**Comment by txomin13** [comment]
@pbauman, @gregrodgers 

I updated my PR #38 such that the most commonly used malloc and memcopy operations
do now accept complex, integer, real SP and DP datatypes with up to 7 dimensions.

The datatype-specific routines use `C_F_POINTER` together with the `shape` argument
to create multi-dimensional Fortran pointers.

Using this, you can write code like the following:

https://github.com/txomin13/hipfort/blob/feature/rocm3.8-modules/test/vecadd/main.f03

Moreover, you can slice arrays with the Fortran pointers and can get their size (per dimension) in length and in bytes.

However, we need to use Fortran 2008 to get this working. Currently, the CMakeLists.txt specifies Fortran 2003.

**Comment by txomin13** [comment]
Feature was added in the latest update of main/master.
